actor CampusManager as x 
participant HTML
participant Component 
participant Service 
participant MGC 

activate x
x -> HTML: option to edit a floor
activate HTML
HTML -> Component: triggers function to get all buildings
activate Component
Component -> Service: calls method to manage the request
activate Service
Service -> MGC: GET /api/building/buildingsList
activate MGC
MGC --> Service: response status and json
deactivate MGC
Service --> Component: returns list of buildings 
deactivate Service
Component --> HTML: returns list of buildings codes
deactivate Component
HTML --> x: displays list of buildings codes
x -> HTML: selects a building code
HTML -> Component: triggers function to get all floors of building selected
activate Component
Component -> Service: calls method to manage the request
activate Service
Service -> MGC: GET /api/building/getBuildingFloors
activate MGC
MGC --> Service: response status and json
deactivate MGC
Service --> Component: returns list of floors
deactivate Service
Component --> HTML: returns list of names of floors
deactivate Component
HTML --> x: displays list of names of floors
x -> HTML: selects a floor name and edits the other parameters
HTML -> Component: triggers function to edit floor
activate Component
Component -> Service: calls method to manage the request
activate Service
Service -> MGC: PATCH /api/floor/updateFloor
activate MGC
MGC --> Service: response status and json
deactivate MGC
Service --> Component: returns edited floor
deactivate Service
Component --> HTML: returns edited floor
deactivate Component
HTML --> x: displays edited floor
deactivate HTML
deactivate x