boundary x 
participant HTML
participant Component 
participant Service 
participant MGC 



x -> HTML: option to get robots by task
activate HTML
HTML -> Component: triggers function to get all tasks
activate Component
Component -> Service: calls method to manage the request
activate Service
Service -> MGC: GET /api/tasks/getAllTasks
activate MGC
MGC --> Service: response status and json
deactivate MGC
Service --> Component: returns list of tasks
deactivate Service
Component --> HTML: returns list of tasks
deactivate Component
HTML --> x: displays list of tasks
x -> HTML: selects a task
HTML -> Component: triggers function to get all robots of task selected
activate Component
Component -> Service: calls method to manage the request
activate Service
Service -> MGC: GET /api/robots/getRobotsByTask
activate MGC
MGC --> Service: response status and json
deactivate MGC
Service --> Component: returns list of robots
deactivate Service
Component --> HTML: returns list of robots
deactivate Component
HTML --> x: displays list of robots
deactivate HTML
