@startuml
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US006

autonumber

actor "System Administrator" as Admin
participant ":System" as System

activate Admin

        Admin -> System : requests to specify a location
    activate System

        System --> Admin : requests data
    deactivate System

        Admin -> System : types requested data (stateAbbreviation)
    activate System

        System --> Admin: shows requested data
    deactivate System

        Admin -> System: submits data
    activate System

        System --> Admin : shows location list and requests confirmation
    deactivate System

        Admin -> System : specify location
    activate System

        System --> Admin: requests confirmation
        deactivate System

        Admin -> System: confirms location
        activate System

        System --> Admin : displays operation success
    deactivate Admin


@enduml