@startuml
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US40

autonumber

actor "Utilizador" as User
participant ":Sistema" as System

activate User

    User -> System : Pede a finalidade da recolha de dados
    activate System

        System --> User : Apresenta Finalidade da Recolha de Dados
    deactivate System

@enduml