boundary x 
participant API
participant System

x -> API: 1. POST -> /api/robot/createRobot
activate API
API -> System: 2. Handles the request
activate System
System -> API: 3. response status and json
deactivate System
API --> x: 2. response status and json
deactivate API