@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

title US006 - Domain Model

class SystemAdministrator {
}

class Location {
   name
}

class State{
}

class District{
}

class City{
}

SystemAdministrator "1" -- "0..*" Location : specifies >
Location "1" - "1" State : has >
State "1" -- "1..*" District
District "1" -- "1..*" City
Location "*" -- "1" System : to >

@enduml