@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "System Administrator" as ADM
participant ":SpecifyLocationUI" as UI
participant ":SpecifyLocationController" as CTRL

activate ADM

        ADM -> UI : requests to specify a location
    activate UI

        UI -> CTRL**: create specify location controller

        UI --> ADM : requests data
    deactivate UI

        ADM -> UI : types requested data (stateAbbreviation)
    activate UI

        UI --> ADM: shows requested data
    deactivate UI

        ADM -> UI: submits data
    activate UI

    UI -> CTRL: checkStoresLocation(stateAbbreviation)
            activate CTRL

                        ref over CTRL
                        Check Stores Location
                        end ref

                CTRL --> UI: location verified
            deactivate CTRL


            UI -> CTRL: findStoresLocation(stateAbbreviation)
        activate CTRL

                ref over CTRL
                Find Stores Location
                end ref

            CTRL --> UI: locations list
        deactivate CTRL

        UI --> ADM : shows locations list
    deactivate UI

        ADM -> UI : selects one of the locations
        activate UI

        UI --> ADM : shows location selected and requests confirmation
deactivate UI

        ADM -> UI : confirms location
    activate UI

        UI --> ADM : displays operation success
    deactivate ADM

deactivate ADM

@enduml